// Q23) Intentional Error: If you haven’t received an array index error in one of your programs yet, try to make one happen. Change an index in one of your programs to produce an index error. Make sure you correct the error before closing the program.
var car = 'subaru';
var country = "pakistan";
var age = 26;
var isAlive = true;
var isNull = null;
var novalue = undefined;
console.log("Is car == 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is age == 26? I predict True.");
console.log(age === 26);
console.log("Is isAlive == true? I predict True.");
console.log(isAlive === true);
console.log("Is isNull == null? I predict True.");
console.log(isNull == null);
console.log("Is !isNan(age)? I predict True.");
console.log(!isNaN(age));
console.log("Is isNull == null? I predict True.");
console.log(isNull == null);
console.log("Is novalue == undefine? I predict True.");
console.log(novalue == undefined);
console.log("Is country == 'subaru'? I predict False.");
console.log(country === 'subaru');
console.log("Is age == 26? I predict False.");
console.log(age === 25);
console.log("Is isAlive !== true? I predict false.");
console.log(isAlive !== true);
console.log("Is isNull !== null? I predict False.");
console.log(isNull !== null);
console.log("Is isNan(age)? I predict False.");
console.log(isNaN(age));
